name: Android CI

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-admin
      with:
        java-version: 1.8
    - name: Magic Link
      run: python scripts/checksnippets.py
    - name: Build with Gradle
      run: ./build.sh
